import Head from 'next/head'
import Link from "next/link"
import Image from 'next/image'
import styles from '../styles/Home.module.css'



export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2{
            font-size:25px;
          }
        `}
      </style>
   
      <Head>
        <title>Hunting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Hunting Coders</a>
        </h1>
        <div className={styles.imgwrapper}>
        <Image className={styles.myimg} src="/img.jpg" width={288} height={200}/>
        </div>
        
      <p className={styles.description}> A blog for hunting coders by hunting coder</p>

       <div className="blogs">
         <h2>Popular blogs</h2>
        <div className="blogItem">
          <h3>How to learn javascript in 2022</h3>
          <p>Javascript is the language used to design logic for the web</p>
        </div>
        <div className="blogItem">
          <h3>How to learn javascript in 2022</h3>
          <p>Javascript is the language used to design logic for the web</p>
        </div>
        <div className="blogItem">
          <h3>How to learn javascript in 2022</h3>
          <p>Javascript is the language used to design logic for the web</p>
        </div>
       </div>


      </main>

      
    </div>
  )
}
